# .github/workflows/compile-css.yml
# Render CSS and Javascript for MetaDocencia varnish
# -------------------------------------------------
# • Se ejecuta en cada push que toque los archivos listados
# • Puede lanzarse manualmente desde la pestaña Actions

name: Render CSS and Javascript

on:
  workflow_dispatch:           # habilita el botón “Run workflow”
  pull_request:
  push:
    branches: [main]
    paths:
      - .github/workflows/compile-css.yml
      - source/**
      - postinstall.sh
      - squash-a-script.sh
      - squash-sass.sh
      - package.json
      - package-lock.json

jobs:
  compress-everything:
    name: Render css/javascript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean previous assets
        run: rm -rf inst/pkgdown/assets/assets/

      - uses: actions/setup-node@v4
        with:
          node-version: '18'        # versión LTS estable

      - run: npm ci                 # instalación reproducible

      - name: Bundle JavaScript
        run: bash squash-a-script.sh

      - name: Compile SCSS to CSS
        run: bash squash-sass.sh

      - name: Commit regenerated assets
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name  "GitHub Actions"
          git add assets/ inst/ || true
          git commit -m 'regenerated css/js' || echo "No changes to commit"
          git push origin HEAD || echo "No changes to commit"
